//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negotiation.Models
{
    using System;
    
    public enum Education : byte
    {
        TwelveYears = 0,
        Bachelor = 1,
        Masters = 2,
        Phd = 3
    }
}
