//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negotiation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameDomainConfig
    {
        public int Id { get; set; }
        public string AiSide { get; set; }
        public string AiVariant { get; set; }
        public string HumanSide { get; set; }
        public string HumanVariant { get; set; }
    
        public virtual GameDomain GameDomain { get; set; }
    }
}
