//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negotiation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.Users = new HashSet<User>();
            this.NegotiationAction = new HashSet<NegotiationAction>();
            this.UserResult = new HashSet<UserResult>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<NegotiationAction> NegotiationAction { get; set; }
        public virtual GameDomain GameDomain { get; set; }
        public virtual ICollection<UserResult> UserResult { get; set; }
    }
}
