//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negotiation.Models
{
    using System;
    
    public enum NegotiationActionType : byte
    {
        Connect = 0,
        MakeChange = 1,
        MakeOffer = 2,
        AcceptOffer = 3,
        Optout = 4,
        OptoutReceive = 5,
        Disconnect = 6
    }
}
