//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negotiation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NegotiationAction
    {
        public int Id { get; set; }
        public NegotiationActionType Type { get; set; }
        public System.TimeSpan RemainingTime { get; set; }
        public string Value { get; set; }
        public string GameId { get; set; }
        public string UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
