//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negotiation.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NegotiationContainer : DbContext
    {
        public NegotiationContainer()
            : base("name=NegotiationContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NegotiationAction> NegotiationActionSet { get; set; }
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<UserRole> UserRoleSet { get; set; }
        public virtual DbSet<Game> GameSet { get; set; }
        public virtual DbSet<GameDomain> GameDomainSet { get; set; }
        public virtual DbSet<Strategy> StrategySet { get; set; }
        public virtual DbSet<DomainVariant> DomainVariantSet { get; set; }
        public virtual DbSet<GameDomainConfig> GameDomainConfigSet { get; set; }
        public virtual DbSet<UserData> UserDataSet { get; set; }
        public virtual DbSet<StrategyConfig> StrategyConfigSet { get; set; }
    }
}
