//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negotiation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string Id { get; set; }
        public UserType Type { get; set; }
        public string GameId { get; set; }
    
        public virtual UserRole UserRole { get; set; }
        public virtual Strategy Strategy { get; set; }
        public virtual UserData UserData { get; set; }
    }
}
