//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negotiation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserData
    {
        public int Id { get; set; }
        public Gender Gender { get; set; }
        public AgeRange AgeRange { get; set; }
        public Education Education { get; set; }
        public string DegreeField { get; set; }
        public string Country { get; set; }
        public string Name { get; set; }
        public long StudentId { get; set; }
        public string University { get; set; }
    }
}
